name: hades-dev

services:
  python:
    build:
      context: ..
      dockerfile: docker/Python.Dockerfile
    restart: unless-stopped
    ports:
      - 8006:8006
    volumes:
      - ..:/srv/app
      - /srv/app

  dependences:
    build:
      context: ..
      dockerfile: docker/Dependences.Dockerfile
    restart: unless-stopped
    volumes_from:
      - python