name: hades

networks:
  internal:

services:
  python:
    build:
      context: ..
      dockerfile: docker/Python.Prod.Dockerfile
    networks:
      - internal
    read_only: true

  nginx:
    # read_only: true
    build:
      context: ..
      dockerfile: docker/Nginx.Dockerfile
    networks:
      - internal
    ports:
      - 8015:8015