name: hades

networks:
  internal:

services:
  python:
    build:
      context: ..
      dockerfile: docker/Python.Prod.Dockerfile
    networks:
      - internal

  nginx:
    build:
      context: ..
      dockerfile: docker/Nginx.Dockerfile
    networks:
      - internal
    ports:
      - 8015:8015